import test from 'node:test';
import assert from 'node:assert/strict';
import { INITIAL_LOCATIONS } from '../src/data.js';
import { buildEquipment } from '../src/equipment.js';
import { defaultConfig } from '../src/administration.js';
import { capabilities } from '../src/access.js';
import { INITIAL_PHASE6, geographicCoordinate, lcsIoState, orderedSchematic, partitionMappedDevices, phase6Reducer, sanitizeLayoutUpdate, validateVmsDraft } from '../src/phase6.js';

const devices=buildEquipment(INITIAL_LOCATIONS),loc=INITIAL_LOCATIONS[0],atLoc=devices.filter(d=>d.locationId===loc.id),vms=atLoc.find(d=>d.type==='Mini VMS');
test('GIS uses only explicitly configured valid geographic coordinates',()=>{const configured={...vms,configuration:{...defaultConfig(vms),latitude:'3.125',longitude:'101.75'}};assert.deepEqual(geographicCoordinate(configured),[101.75,3.125]);assert.equal(geographicCoordinate(vms),null);});
test('GIS partition keeps unconfigured equipment discoverable',()=>{const configured={...vms,configuration:{...defaultConfig(vms),latitude:3,longitude:101}};const p=partitionMappedDevices([configured,...atLoc.filter(d=>d.id!==vms.id)]);assert.equal(p.mapped.length,1);assert.equal(p.mapped.length+p.unmapped.length,atLoc.length);});
test('schematic ordering uses chainage and stable IDs rather than array index',()=>{const reversed=[...atLoc].reverse(),a=orderedSchematic(reversed),b=orderedSchematic(atLoc);assert.deepEqual(a.map(x=>x.device.id),b.map(x=>x.device.id));assert.ok(a.every((x,i)=>i===0||(a[i-1].placement.chainageKm??Infinity)<=(x.placement.chainageKm??Infinity)));});
test('LCS I/O relationship remains keyed by associated LCS ID',()=>{const rows=lcsIoState(atLoc);assert.ok(rows.length);assert.ok(rows.every(r=>r.io?.associatedLcsId===r.lcs.id));});
test('LCS commanded and reported mismatch is explicit',()=>{const lcs=atLoc.find(d=>d.type==='LCS'),io=atLoc.find(d=>d.associatedLcsId===lcs.id);const [row]=lcsIoState([{...lcs,indication:'Green Arrow',observedIndication:'Red X'},io]);assert.equal(row.mismatch,true);assert.equal(row.state,'Mismatch');});
test('final VMS requires positive remaining distance and capability limits are explicit',()=>{assert.match(validateVmsDraft({line1:'OPEN',line2:'',role:'Final/exit',remainingDistanceMeters:''},{lines:2}).join(' '),/positive remaining distance/);assert.deepEqual(validateVmsDraft({line1:'OPEN',line2:'500M',role:'Final/exit',remainingDistanceMeters:500},{lines:2}),[]);});
test('saved templates reload by location, device and phase without changing reported display',()=>{const draft={line1:'TEST',line2:'MESSAGE',role:'Start/entry',remainingDistanceMeters:''};const s=phase6Reducer(INITIAL_PHASE6,{type:'VMS_TEMPLATE_SAVE',locationId:loc.id,deviceId:vms.id,deviceType:'Mini VMS',phase:2,draft,actorId:'A',now:1});assert.equal(s.templates[`${loc.id}|${vms.id}|2`].line1,'TEST');assert.equal(vms.sign.msg,atLoc.find(d=>d.id===vms.id).sign.msg);});
test('publish resolution records per-device success, partial and failed outcomes',()=>{for(const scenario of ['success','partial','failed']){let s=phase6Reducer(INITIAL_PHASE6,{type:'VMS_PUBLISH_REQUEST',locationId:loc.id,deviceIds:['a','b'],phase:1,scenario,actorId:'A',now:1});s=phase6Reducer(s,{type:'VMS_PUBLISH_RESOLVE',id:s.publishJobs[0].id,actorId:'A',now:2});assert.equal(s.publishJobs[0].results.length,2);assert.equal(s.publishJobs[0].status,scenario==='success'?'Simulated success':scenario==='partial'?'Partial':'Failed');}});
test('location and persona capability isolation remains unchanged',()=>{const person={id:'x',role:'System Administrator',active:true,locationIds:[loc.id]};assert.equal(capabilities(person,loc.id).vmsEdit,true);assert.equal(capabilities(person,INITIAL_LOCATIONS[1].id).read,false);});
test('Road Studio updates cannot replace telemetry or operation state',()=>{const clean=sanitizeLayoutUpdate({roadPath:[{x:1,y:2}],equipmentList:[],traffic:[{spd:80}],operation:{phase:2},status:'active',los:'A'});assert.deepEqual(clean,{roadPath:[{x:1,y:2}],equipmentList:[]});});
