import React, { useMemo, useState } from 'react';
import { REPORT_TEMPLATES, aggregateAvds, archiveEligibility, sampleAvdsHistory, auditInRange } from '../phase5';

const fmt = value => value == null ? 'Missing' : Number(value).toFixed(1);
const Field = ({ label, children }) => <label className="p5-field"><span>{label}</span>{children}</label>;
const State = ({ title, children }) => <div className="p5-state"><strong>{title}</strong><p>{children}</p></div>;

export function Reports({ loc, devices, auditLogs, operations, state, dispatch, actorId, now }) {
  const [criteria, setCriteria] = useState({ template: 'health', period: 'Weekly', format: 'PDF', locationId: loc.id, user: '', from: '', to: '' });
  const template = REPORT_TEMPLATES[criteria.template];
  const rows = useMemo(() => {
    if (criteria.template === 'health') return devices.filter(d => d.locationId === criteria.locationId).map(d => ({ equipmentId: d.id, description: d.description || d.name, timestamp: d.lastObservedAt || d.observedAt || 'Not supplied', status: d.status || d.connectivity, remarks: d.statusReason || 'Sample/prototype observation' }));
    if (criteria.template === 'activation') {
      const op = operations?.byId?.[criteria.locationId], ev = (operations?.events || []).filter(e => e.locationId === criteria.locationId);
      return ev.length ? [{ timestamp: ev.at(-1)?.timestamp, preActivationTimestamp: ev.find(e => /activation requested/i.test(e.action))?.timestamp || 'Not recorded', activationTimestamp: ev.find(e => /activated/i.test(e.action))?.timestamp || 'Not recorded', preDeactivationTimestamp: ev.find(e => /deactivation requested/i.test(e.action))?.timestamp || 'Not recorded', deactivationTimestamp: ev.find(e => /deactivated/i.test(e.action))?.timestamp || 'Not recorded', postDeactivationTimestamp: 'Not recorded', equipmentStatus: op?.lastResult || 'Not supplied', radarVehicleVolumeAtSinglePoint: devices.find(d => d.locationId === criteria.locationId && d.type === 'AVDS')?.volume ?? 'Missing', remarks: 'Prototype event reconstruction; verify against backend event schema.' }] : [];
    }
    return auditLogs.filter(x => (!criteria.user || String(x.initiator || x.actor).toLowerCase().includes(criteria.user.toLowerCase())) && (criteria.period !== 'By Date' || auditInRange(x, criteria.from, criteria.to))).map(x => ({ timestamp: x.timestamp, user: x.initiator || x.actor, module: x.module, activity: x.activity, location: x.location, equipmentId: x.equipmentId, result: x.result }));
  }, [criteria, devices, operations, auditLogs]);
  const create = () => dispatch({ type: 'REPORT_CREATE', criteria, rows, actorId, now });
  return <div className="p5-grid"><section className="panel p5-card"><h2>Report request</h2><p className="p5-note">Prototype job lifecycle. Inputs and rows are snapshotted when queued.</p>
    <Field label="Template"><select value={criteria.template} onChange={e => setCriteria({ ...criteria, template: e.target.value, period: 'Weekly' })}>{Object.entries(REPORT_TEMPLATES).map(([id,t])=><option key={id} value={id}>{t.name}</option>)}</select></Field>
    <Field label="Period"><select value={criteria.period} onChange={e=>setCriteria({...criteria,period:e.target.value})}>{template.periods.map(x=><option key={x}>{x}</option>)}</select></Field>
    {criteria.period === 'By User' && <Field label="User contains"><input value={criteria.user} onChange={e=>setCriteria({...criteria,user:e.target.value})}/></Field>}
    {criteria.period === 'By Date' && <><Field label="From"><input type="datetime-local" value={criteria.from} onChange={e=>setCriteria({...criteria,from:e.target.value})}/></Field><Field label="To"><input type="datetime-local" value={criteria.to} onChange={e=>setCriteria({...criteria,to:e.target.value})}/></Field></>}
    <Field label="Requested format"><select value={criteria.format} onChange={e=>setCriteria({...criteria,format:e.target.value})}><option>PDF</option><option>Excel</option></select></Field>
    <button className="gen-btn" onClick={create}>Queue report ({rows.length} rows)</button>{state.feedback&&<p role="status">{state.feedback}</p>}<p className="p5-note">PDF/Excel file generation requires Laravel and is unavailable in this frontend prototype.</p></section>
    <section className="panel p5-card"><h2>Generated reports</h2>{!state.reports.length?<State title="No report jobs">Choose criteria and queue a report.</State>:state.reports.map(r=><article className="p5-record" key={r.id}><b>{r.id} Â· {REPORT_TEMPLATES[r.criteria.template].name}</b><span className={`p5-status ${r.status.toLowerCase().replace(' ','-')}`}>{r.status}</span><small>{r.criteria.period} Â· {r.rows.length} rows Â· snapshot {r.createdAt}</small>{r.error&&<p role="alert">{r.error}</p>}<div><button disabled={!['Queued','Generating'].includes(r.status)} onClick={()=>dispatch({type:'REPORT_ADVANCE',id:r.id,actorId,now})}>Advance demo status</button> <button disabled={!['Queued','Generating'].includes(r.status)} onClick={()=>dispatch({type:'REPORT_FAIL',id:r.id,actorId,now})}>Simulate failure</button> <button disabled={r.status!=='Failed'} onClick={()=>dispatch({type:'REPORT_RETRY',id:r.id,actorId,now})}>Retry</button> <button disabled={r.status!=='Ready'} onClick={()=>window.print()}>Print preview / save as PDF</button></div><details><summary>Preview snapshot</summary><pre>{JSON.stringify(r.rows.slice(0,10),null,2)}</pre></details></article>)}</section></div>;
}

export function AvdsAnalytics({ loc, devices, now }) {
  const [interval, setIntervalMinutes] = useState(5), [metric,setMetric]=useState('speed'), [deviceId,setDeviceId]=useState('all');
  const history = useMemo(()=>sampleAvdsHistory(devices,now),[devices,now]);
  const filtered=history.filter(p=>p.locationId===loc.id&&(deviceId==='all'||p.deviceId===deviceId));
  const points=aggregateAvds(filtered,interval), values=points.map(p=>p[metric]), numeric=values.filter(Number.isFinite), max=Math.max(...numeric,1);
  const path=points.map((p,i)=>Number.isFinite(p[metric])?`${i?'L':'M'} ${10+i*(480/Math.max(points.length-1,1))} ${170-(p[metric]/max)*140}`:null).filter(Boolean).join(' ');
  const avds=devices.filter(d=>d.locationId===loc.id&&d.type==='AVDS');
  return <div className="p5-stack"><section className="panel p5-card"><h2>AVDS traffic analytics</h2><p className="p5-note">Sample historical fixture Â· Asia/Kuala_Lumpur display intent. Lane metadata and configured congestion thresholds are not supplied.</p><div className="p5-controls"><Field label="Device"><select value={deviceId} onChange={e=>setDeviceId(e.target.value)}><option value="all">All authorized AVDS</option>{avds.map(d=><option key={d.id} value={d.id}>{d.id}</option>)}</select></Field><Field label="Aggregation"><select value={interval} onChange={e=>setIntervalMinutes(Number(e.target.value))}><option value="5">5 minutes</option><option value="15">15 minutes</option><option value="60">60 minutes</option></select></Field><Field label="Metric"><select value={metric} onChange={e=>setMetric(e.target.value)}><option value="speed">Mean speed (km/h)</option><option value="volume">Vehicle volume / interval</option><option value="occupancy">Mean occupancy (%)</option></select></Field></div>
    {!avds.length?<State title="No AVDS at this location">No historical series can be shown.</State>:<><svg className="p5-chart" viewBox="0 0 500 190" role="img" aria-label={`${metric} time series`}><line x1="10" y1="170" x2="490" y2="170"/><path d={path}/></svg><p>{numeric.length} populated buckets Â· {points.length-numeric.length} missing buckets preserved (never converted to zero).</p><div className="p5-table-wrap"><table><thead><tr><th>Timestamp</th><th>Speed</th><th>Volume / {interval} min</th><th>Occupancy</th><th>Lane</th></tr></thead><tbody>{points.slice(-12).map((p,i)=><tr key={i}><td>{p.timestamp}</td><td>{fmt(p.speed)}</td><td>{fmt(p.volume)}</td><td>{fmt(p.occupancy)}</td><td>Not supplied</td></tr>)}</tbody></table></div></>}</section><section className="panel p5-card"><h3>Before / during / after comparison</h3><State title="Needs completed operation boundaries">The proposed comparison uses 30 minutes before and after an operation. Backend operation timestamps and lane mapping are required for a valid comparison.</State></section></div>;
}

export function Maintenance({ loc, devices, state, dispatch, actorId, now, healthOnly=false, editable=true }) {
  const assets=[...devices.filter(d=>d.locationId===loc.id),{id:'SYS-APP-DEMO',name:'Smartlane application service',locationId:loc.id,type:'System'}];
  const [record,setRecord]=useState({locationId:loc.id,assetId:assets[0]?.id||'',remarks:'',actions:'',status:'Open'});
  if(healthOnly) return <div className="p5-stack"><section className="panel p5-card"><h2>System health</h2><p className="p5-note">Sample observations. Health does not change when a maintenance record is completed.</p><div className="p5-health"><article><b>Application service</b><span className="p5-status ready">Available</span><small>Response time 128 ms Â· observed {new Date(now-60000).toISOString()}</small></article><article><b>Storage capacity</b><span className="p5-status generating">Warning</span><small>78% used Â· sample warning threshold 75% Â· observed {new Date(now-120000).toISOString()}</small></article><article><b>Archive connector</b><span className="p5-status no-data">Unknown</span><small>No telemetry source connected; observation unavailable.</small></article></div></section></div>;
  return <div className="p5-grid"><section className="panel p5-card"><h2>Maintenance activity</h2>{!editable&&<p className="p5-note">Read-only for this demo role.</p>}<Field label="Asset"><select value={record.assetId} onChange={e=>setRecord({...record,assetId:e.target.value})}>{assets.map(a=><option key={a.id} value={a.id}>{a.id} Â· {a.name}</option>)}</select></Field><Field label="Remarks"><textarea value={record.remarks} onChange={e=>setRecord({...record,remarks:e.target.value})}/></Field><Field label="Actions taken / planned"><textarea value={record.actions} onChange={e=>setRecord({...record,actions:e.target.value})}/></Field><Field label="Completion status"><select value={record.status} onChange={e=>setRecord({...record,status:e.target.value})}><option>Open</option><option>In progress</option><option>Completed</option></select></Field><button disabled={!editable} onClick={()=>dispatch({type:'MAINTENANCE_SAVE',record,actorId,now})}>Save simulated record</button>{state.feedback&&<p role="status">{state.feedback}</p>}</section><section className="panel p5-card"><h2>History</h2>{!state.maintenance.length?<State title="No maintenance records">Create a record with remarks and an explicit action.</State>:state.maintenance.filter(r=>r.locationId===loc.id).map(r=><article className="p5-record" key={r.id}><b>{r.id} Â· {r.assetId}</b><span className="p5-status">{r.status}</span><p>{r.remarks}</p><small>{r.actions} Â· {r.updatedAt} Â· {r.actorId}</small></article>)}</section></div>;
}

export function Housekeeping({ loc, state, dispatch, actorId, now, onAdmin, devices }) {
  const [category,setCategory]=useState('Operational'), [text,setText]=useState(''), [preview,setPreview]=useState(null);
  const sampleRecords=[{category:'Operational',timestamp:new Date(now-800*86400000).toISOString()},{category:'Operational',timestamp:new Date(now-20*86400000).toISOString()},{category:'CCTV',timestamp:new Date(now-40*86400000).toISOString()},{category:'Configuration',timestamp:new Date(now-900*86400000).toISOString()}];
  const eligibility=archiveEligibility(sampleRecords,category,now);
  const parse=()=>{try{const raw=JSON.parse(text),rows=Array.isArray(raw)?raw:[raw]; const allowed=['id','name','description','model','ip','latitude','longitude','enabled','parameterNotes','pollingIntervalSeconds']; const errors=[]; rows.forEach((r,i)=>{const device=devices.find(d=>d.id===r.id&&d.locationId===loc.id); if(!device) errors.push(`Row ${i+1}: device is outside this location or missing.`); const unknown=Object.keys(r).filter(k=>!allowed.includes(k)); if(unknown.length) errors.push(`Row ${i+1}: unsupported fields ${unknown.join(', ')}.`);}); setPreview({rows,errors});}catch{setPreview({rows:[],errors:['Enter a valid JSON object or array.']});}};
  const apply=()=>onAdmin({type:'CONFIG_IMPORT',locationId:loc.id,records:preview.rows,token:`import-${now}`});
  return <div className="p5-grid"><section className="panel p5-card"><h2>Configuration import</h2><p className="p5-note">Bounded JSON import for equipment configuration metadata. Credentials and telemetry fields are rejected. Preview and validation occur before one atomic simulated save.</p><textarea className="p5-import" value={text} onChange={e=>{setText(e.target.value);setPreview(null)}} placeholder='[{"id":"...","name":"...","description":"...","model":"...","ip":"10.0.0.1","latitude":3.1,"longitude":101.7,"enabled":true}]'/><button onClick={parse}>Parse and preview</button>{preview&&<div><p>{preview.rows.length} rows parsed.</p>{preview.errors.map(e=><p role="alert" key={e}>{e}</p>)}<button disabled={!!preview.errors.length} onClick={apply}>Confirm atomic import</button><pre>{JSON.stringify(preview.rows,null,2)}</pre></div>}</section><section className="panel p5-card"><h2>Archive / offload simulation</h2><Field label="Record category"><select value={category} onChange={e=>setCategory(e.target.value)}><option>Operational</option><option>CCTV</option><option>Configuration</option></select></Field>{eligibility.reason?<State title="Not eligible">{eligibility.reason}</State>:<p>{eligibility.eligible.length} sample records eligible Â· cutoff {eligibility.cutoff} Â· retained for at least {eligibility.retentionDays} days.</p>}<button disabled={!eligibility.eligible.length} onClick={()=>dispatch({type:'ARCHIVE_QUEUE',actorId,now,snapshot:{locationId:loc.id,category,cutoff:eligibility.cutoff,eligibleCount:eligibility.eligible.length}})}>Queue non-destructive simulation</button>{state.archiveJobs.map(j=><article className="p5-record" key={j.id}><b>{j.id} Â· {j.snapshot.category}</b><span className="p5-status">{j.status}</span><small>{j.snapshot.eligibleCount} snapshotted records Â· {j.destination}</small><button disabled={!['Queued','Running'].includes(j.status)} onClick={()=>dispatch({type:'ARCHIVE_ADVANCE',id:j.id,actorId,now})}>Advance demo status</button></article>)}</section></div>;
}

export default function Phase5({ kind, ...props }) {
  if(kind==='reports') return <Reports {...props}/>;
  if(kind==='analytics') return <AvdsAnalytics {...props}/>;
  if(kind==='maintenance') return <Maintenance {...props}/>;
  if(kind==='health') return <Maintenance {...props} healthOnly/>;
  return <Housekeeping {...props}/>;
}

