import React, { useState } from 'react';
import { EMPTY_REPORT_MESSAGE, REPORT_FORMATS, REPORT_PERIODS, REPORT_TYPES, createReportSnapshot } from '../reports';
import { downloadReportFile, generateReportFile } from '../reportFiles';

const Field = ({ label, children }) => <label className="p5-field"><span>{label}</span>{children}</label>;
const State = ({ title, children }) => <div className="p5-state"><strong>{title}</strong><p>{children}</p></div>;

export default function Reports({ loc, devices, auditLogs, operations, actorId }) {
  const [criteria, setCriteria] = useState({ type: 'health', period: 'Weekly', format: 'PDF' });
  const [generated, setGenerated] = useState(null);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState('');
  const create = async () => {
    if (generating || !REPORT_TYPES.some(type => type.id === criteria.type) || !REPORT_PERIODS.includes(criteria.period) || !REPORT_FORMATS.includes(criteria.format)) return;
    setGenerating(true); setError('');
    try {
      await Promise.resolve();
      const report = createReportSnapshot({ ...criteria, location: loc, actorId, now: Date.now(), devices, operations, auditLogs });
      setGenerated({ report, file: generateReportFile(report) });
    } catch (generationError) {
      setGenerated(null); setError(`Report generation failed: ${generationError.message}`);
    } finally { setGenerating(false); }
  };
  const change = (field, value) => { setCriteria(current => ({ ...current, [field]: value })); setGenerated(null); setError(''); };

  return <div className="p5-grid reports-mvp">
    <section className="panel p5-card report-generator"><h2>Generate Report</h2>
      <Field label="Selected Smartlane location"><output>{loc.name}</output></Field>
      <Field label="Report Type"><select value={criteria.type} onChange={event => change('type', event.target.value)}>{REPORT_TYPES.map(type => <option key={type.id} value={type.id}>{type.label}</option>)}</select></Field>
      <Field label="Period"><select value={criteria.period} onChange={event => change('period', event.target.value)}>{REPORT_PERIODS.map(period => <option key={period}>{period}</option>)}</select></Field>
      <Field label="Output Format"><select value={criteria.format} onChange={event => change('format', event.target.value)}>{REPORT_FORMATS.map(format => <option key={format}>{format}</option>)}</select></Field>
      <button className="gen-btn" disabled={generating} onClick={create}>{generating ? 'Generating…' : 'Generate Report'}</button>
      {error && <p role="alert">{error}</p>}
    </section>
    <section className="panel p5-card report-preview"><h2>Report Preview</h2>
      {!generated ? <State title="No report generated">Select the report type, period and format, then generate a preview.</State> : <>
        <header className="report-preview-header"><h3>{generated.report.title}</h3><dl>
          <div><dt>Smartlane location</dt><dd>{generated.report.location}</dd></div><div><dt>Direction</dt><dd>{generated.report.direction}</dd></div>
          <div><dt>Selected period</dt><dd>{generated.report.period}</dd></div><div><dt>Generated by</dt><dd>{generated.report.generatedBy}</dd></div>
          <div><dt>Generated timestamp</dt><dd>{new Date(generated.report.generatedAt).toLocaleString('en-MY')}</dd></div><div><dt>Total records</dt><dd>{generated.report.totalRecords}</dd></div>
        </dl>{generated.report.snapshotNotice && <p className="p5-note">{generated.report.snapshotNotice}</p>}</header>
        {!generated.report.rows.length ? <State title="No records">{EMPTY_REPORT_MESSAGE}</State> : <div className="p5-table-wrap report-table-wrap"><table><thead><tr>{generated.report.columns.map(([key, label]) => <th key={key}>{label}</th>)}</tr></thead><tbody>{generated.report.rows.slice(0, 25).map((row, index) => <tr key={index}>{generated.report.columns.map(([key]) => <td key={key}>{row[key]}</td>)}</tr>)}</tbody></table>{generated.report.rows.length > 25 && <p className="p5-note">Showing the first 25 of {generated.report.totalRecords} records. The download contains all records.</p>}</div>}
        <button className="gen-btn report-download" onClick={() => downloadReportFile(generated.report, generated.file)}>Download {generated.report.format}</button>
      </>}
    </section>
  </div>;
}
