import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';

const pdfText = value => String(value ?? '—').replace(/[–—]/g, '-').replace(/·/g, '-');
const metadata = report => [
  ['Smartlane Management System'],
  [report.title],
  [`Location: ${report.location}`],
  [`Direction: ${report.direction}`],
  [`Period: ${report.period}`],
  [`Generated by: ${report.generatedBy}`],
  [`Generated at: ${new Date(report.generatedAt).toLocaleString('en-MY')}`],
  [`Total records: ${report.totalRecords}`],
  ...(report.snapshotNotice ? [[report.snapshotNotice]] : []),
];

export const reportTableRows = report => report.rows.map(row => report.columns.map(([key]) => row[key]));

export function generatePdfBytes(report) {
  const landscape = report.columns.length > 6;
  const doc = new jsPDF({ orientation: landscape ? 'landscape' : 'portrait', unit: 'mm', format: 'a4' });
  doc.setFont('helvetica', 'bold'); doc.setFontSize(15); doc.text('Smartlane Management System', 14, 14);
  doc.setFontSize(12); doc.text(pdfText(report.title), 14, 21);
  doc.setFont('helvetica', 'normal'); doc.setFontSize(8.5);
  const details = metadata(report).slice(2).map(row => pdfText(row[0]));
  details.forEach((line, index) => doc.text(line, 14, 28 + index * 4.5));
  const startY = 31 + details.length * 4.5;
  autoTable(doc, {
    startY,
    head: [report.columns.map(([, label]) => pdfText(label))],
    body: reportTableRows(report).map(row => row.map(pdfText)),
    styles: { font: 'helvetica', fontSize: landscape ? 6.2 : 7, cellPadding: 1.4, overflow: 'linebreak' },
    headStyles: { fillColor: [30, 64, 175], textColor: 255 },
    margin: { left: 10, right: 10, bottom: 12 },
    didDrawPage: data => {
      doc.setFontSize(8); doc.setTextColor(90);
      doc.text(`Page ${data.pageNumber}`, doc.internal.pageSize.getWidth() - 22, doc.internal.pageSize.getHeight() - 6);
    },
  });
  return new Uint8Array(doc.output('arraybuffer'));
}

export function generateExcelBytes(report) {
  const rows = [...metadata(report), [], report.columns.map(([, label]) => label), ...reportTableRows(report)];
  const worksheet = XLSX.utils.aoa_to_sheet(rows);
  worksheet['!cols'] = report.columns.map(([, label], index) => ({ wch: Math.min(45, Math.max(label.length + 2, ...report.rows.map(row => String(row[report.columns[index][0]] ?? '').length + 2))) }));
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, report.type === 'activation' ? 'Activation Report' : report.type === 'audit' ? 'Audit Trail' : 'Equipment Health');
  return XLSX.write(workbook, { type: 'array', bookType: 'xlsx' });
}

export function generateReportFile(report) {
  const bytes = report.format === 'Excel' ? generateExcelBytes(report) : generatePdfBytes(report);
  return { bytes, mime: report.format === 'Excel' ? 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' : 'application/pdf' };
}

export function downloadReportFile(report, file) {
  const url = URL.createObjectURL(new Blob([file.bytes], { type: file.mime }));
  const anchor = document.createElement('a');
  anchor.href = url; anchor.download = report.filename; anchor.click();
  setTimeout(() => URL.revokeObjectURL(url), 0);
}
